/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestorsupermercadoinventario.ventanas;

import gestorsupermercadoinventario.Gestor;

/**
 *
 * @author mati1
 */
public class VentanaInicio extends javax.swing.JFrame {
    private Gestor gestor; 
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio(Gestor gestor) {
        
        initComponents();
        this.gestor = gestor; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msjBienvenida = new javax.swing.JLabel();
        btnMenuProveedor = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        imgSupermarket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msjBienvenida.setFont(new java.awt.Font("Noteworthy", 0, 20)); // NOI18N
        msjBienvenida.setText("Bienvenid@ al gestor de inventario de supermecado");
        getContentPane().add(msjBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        btnMenuProveedor.setFont(new java.awt.Font("Noteworthy", 0, 18)); // NOI18N
        btnMenuProveedor.setText("Menú Proveedor");
        btnMenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 150, 40));

        exit.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 90, 30));

        imgSupermarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supermarket.png"))); // NOI18N
        getContentPane().add(imgSupermarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Este método se llama cuando se hace clic en el botón "Menú Proveedor".
    * Crea una nueva instancia de la ventana del menú de proveedores, la ajusta al tamaño de su contenido,
    * la centra en la pantalla, la muestra y cierra la ventana actual.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void btnMenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProveedorActionPerformed
        // TODO add your handling code here:
        VentanaProveedor newVproveedor = new VentanaProveedor(this.gestor);
        newVproveedor.pack(); 
        newVproveedor.setLocationRelativeTo(null);
        newVproveedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuProveedorActionPerformed

    /**
    * Este método se llama cuando se hace clic en el botón "Salir".
    * Cierra la aplicación completa al invocar el método System.exit(0).
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        // Cerrar la aplicación completa
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gestor gestor = null;
                new VentanaInicio(gestor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuProveedor;
    private javax.swing.JButton exit;
    private javax.swing.JLabel imgSupermarket;
    private javax.swing.JLabel msjBienvenida;
    // End of variables declaration//GEN-END:variables
}
