/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestorsupermercadoinventario.ventanas;

import gestorsupermercadoinventario.Gestor;
import gestorsupermercadoinventario.Producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class VentanaFiltrarProducto extends javax.swing.JFrame {
    private Gestor gestor;
    /**
     * Creates new form VentanaFiltrarProducto
     */
    public VentanaFiltrarProducto(Gestor gestor) {
        initComponents();
        this.gestor = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backToMenu = new javax.swing.JButton();
        msj1 = new javax.swing.JLabel();
        msj2 = new javax.swing.JLabel();
        cantMinima = new javax.swing.JTextField();
        cantMaxima = new javax.swing.JTextField();
        filtrarProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/superLogo (1) (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Noteworthy", 0, 18)); // NOI18N
        jLabel1.setText("Filtrar producto por stock");

        backToMenu.setText("Volver a Menú");
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });

        msj1.setText("Ingrese la cantidad mínima de stock :  ");

        msj2.setText("Ingrese la cantidad máxima de stock : ");

        filtrarProd.setText("Filtrar");
        filtrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarProdActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backToMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(msj1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(logo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addComponent(msj2)
                                    .addComponent(cantMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(cantMinima)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(filtrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logo)))
                .addGap(30, 30, 30)
                .addComponent(msj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msj2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(filtrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(backToMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Este método se llama cuando se hace clic en el botón "Filtrar".
    * Realiza una filtración de productos por stock en función de los valores ingresados por el usuario.
    * Muestra los productos que cumplen con el rango de stock en un cuadro de diálogo y en un área de texto.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void filtrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarProdActionPerformed
        // TODO add your handling code here:
        int cantMaxStock;
        int cantMinStock;
        
        try {
            cantMinStock = Integer.parseInt(cantMinima.getText());
            if (cantMinStock < 0) {
                JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número entero válido y mayor que 0.");
                return;
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número entero válido.");
            return;
        }
        
        try {
            cantMaxStock = Integer.parseInt(cantMaxima.getText());
            if (cantMinStock < 0) {
                JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número entero válido y mayor que 0.");
                return;
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número entero válido.");
            return;
        }
        
        ArrayList<Producto> productosFiltrados = gestor.filtrarProductosPorStock(cantMinStock, cantMaxStock);
        
        if(productosFiltrados.isEmpty() == true){
            JOptionPane.showMessageDialog(null,"No hay Productos con Stock entre " + cantMinStock + " y " + cantMaxStock + ":");
        }
        else{
            JOptionPane.showMessageDialog(null,"Productos con Stock entre " + cantMinStock + " y " + cantMaxStock + ":");
            
            StringBuilder productosText = new StringBuilder();
            productosText.append("PRODUCTOS CON STOCK ENTRE ").append(cantMinStock).append(" Y ").append(cantMaxStock).append(":\n");
            productosText.append("========================================\n");
            
            for (Producto productoActual : productosFiltrados) {
                productosText.append(productoActual.obtenerInformacion()).append("\n");
                productosText.append("========================================\n");
            }

            // Actualizar el JTextArea con la información acumulada
            jTextArea1.setText(productosText.toString());
            
            
        }
        
    }//GEN-LAST:event_filtrarProdActionPerformed

    /**
    * Este método se llama cuando se hace clic en el botón "volver a Menú".
    * Crea una nueva instancia de la ventana del menú de proveedores, la centra en la pantalla,
    * la muestra y cierra la ventana actual.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
        // TODO add your handling code here:
        VentanaProveedor newMenu = new VentanaProveedor(this.gestor); 
        newMenu.setLocationRelativeTo(null);
        newMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gestor gestor = null;
                new VentanaFiltrarProducto(gestor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenu;
    private javax.swing.JTextField cantMaxima;
    private javax.swing.JTextField cantMinima;
    private javax.swing.JButton filtrarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel msj1;
    private javax.swing.JLabel msj2;
    // End of variables declaration//GEN-END:variables
}
